/// <mls fileReference="_102020_/l2/agentImplementGenome/agentSelectGroups.ts" enhancement="_102027_/l2/enhancementAgent"/>

// Fase B — Agent1: per-organism GROUP selection (LLM). One per page.
// Decides which molecule GROUPS each organism needs (NOT the variant — that is Agent2,
// agentSelectVariant). Writes `groupSelections` to the page defs for Agent2 to consume.

import { IAgentAsync, IAgentMeta } from '/_102027_/l2/aiAgentBase.js';
import { buildWorkItem } from '/_102020_/l2/dsMatch/derivePaths.js';
import { buildGroupList } from '/_102020_/l2/dsMatch/groupCatalog.js';
import { loadPageSource, loadPageDefinitionText, buildAgent1HumanPrompt, validateAgent1Output } from '/_102020_/l2/dsMatch/agent1.js';
import { parseStepArgs, mkCompleted, mkFail, saveFile } from '/_102020_/l2/agentImplementGenome/planning.js';

export function createAgent(): IAgentAsync {
  return {
    agentName: 'agentSelectGroups',
    agentProject: 102020,
    agentFolder: 'agentImplementGenome',
    agentDescription: 'Select which molecule groups each organism of a page needs (Agent1)',
    visibility: 'private',
    beforePromptStep,
    afterPromptStep,
  };
}

async function beforePromptStep(
  agent: IAgentMeta,
  context: mls.msg.ExecutionContext,
  parentStep: mls.msg.AIAgentStep,
  step: mls.msg.AIAgentStep,
  hookSequential: number,
  args?: string,
): Promise<mls.msg.AgentIntent[]> {

  const a = parseStepArgs(args ?? step.prompt);
  const project = mls.actualProject || 0;
  const item = buildWorkItem(project, a.module, a.layout, a.ds, a.page!, a.device);

  const pageSource = await loadPageSource(item.tsOrigem);
  const definitionText = await loadPageDefinitionText(item.tsOrigem);
  const groups = await buildGroupList();
  const humanPrompt = buildAgent1HumanPrompt(item.tsOrigem, pageSource, definitionText, groups);

  const continueParallel: mls.msg.AgentIntentPromptReady = {
    type: 'prompt_ready',
    args: args ?? step.prompt,
    messageId: context.message.orderAt,
    threadId: context.message.threadId,
    taskId: context.task?.PK || '',
    hookSequential,
    parentStepId: parentStep.stepId,
    humanPrompt,
    systemPrompt: system1,
  };

  return [continueParallel];
}

async function afterPromptStep(
  agent: IAgentMeta,
  context: mls.msg.ExecutionContext,
  parentStep: mls.msg.AIAgentStep,
  step: mls.msg.AIAgentStep,
  hookSequential: number,
): Promise<mls.msg.AgentIntent[]> {

  try {
    const payload = step.interaction?.payload?.[0];
    if (payload?.type !== 'flexible' || !payload.result) throw new Error(`invalid payload: ${JSON.stringify(payload)}`);

    const a = parseStepArgs(step.prompt);
    const project = mls.actualProject || 0;
    const item = buildWorkItem(project, a.module, a.layout, a.ds, a.page!, a.device);

    const groups = await buildGroupList();
    const validGroups = new Set(groups.map(g => g.group));
    const validated = validateAgent1Output(payload.result, validGroups, item.defsDestino);

    if (!context.isTest) await saveFile(item.defsDestino, buildGroupSelectionsDefs(item.defsDestino, validated.perOrganism));

    return [mkCompleted(context, parentStep, step, hookSequential)];
  } catch (error) {
    return [mkFail(context, parentStep, step, hookSequential, `[agentSelectGroups] ${error instanceof Error ? error.message : String(error)}`)];
  }
}

/** The intermediate handoff: which groups each organism needs (consumed by agentSelectVariant). */
function buildGroupSelectionsDefs(defsRef: string, perOrganism: unknown): string {
  const cleanRef = defsRef.startsWith('/') ? defsRef.slice(1) : defsRef;
  return [
    `/// <mls fileReference="${cleanRef}" enhancement="_blank"/>`,
    '',
    '// Generated by agentSelectGroups (Agent1). Groups chosen per organism.',
    '// Consumed by agentSelectVariant (Agent2), which picks the concrete molecule variant.',
    '',
    `export const groupSelections = ${JSON.stringify(perOrganism, null, 2)} as const;`,
    '',
  ].join('\n');
}

const system1 = `
<!-- modelType: codeinstruct -->

You must return ONLY a valid JSON object. No preamble, no markdown fences. Start with { and end with }

## Task
You are given the page's RENDERED source (a Lit component with HTML + Tailwind) and the
page definition (sections, organisms, fields). For each organism, decide which molecule
GROUPS are needed to replace the hand-built UI elements that belong to it. Base the
decision on the ACTUAL elements in the rendered HTML, mapped to the organism they sit in.
Use the organismName values from the page definition.

## Rules
- Map a group only when its purpose DIRECTLY and OBVIOUSLY matches a real UI element.
- An organism may need several groups, one, or none. Shorter accurate beats longer wrong.
- Choose group names EXACTLY as listed (camelCase). Never invent a group; omit if none fits.
- Decide GROUPS only — the concrete variant/molecule is chosen later (Agent2).

## Output format
[[OutputSection]]
`;

//#region OutputSection
export type Output = {
  type: 'flexible';
  result: {
    path: string;
    perOrganism: Array<{ organismName: string; groups: string[] }>;
  };
};
//#endregion
