/// <mls fileReference="_102020_/l2/aura/molecules/agentSyncMoleculeCatalog/helpers/syRenderSkill.ts" enhancement="_blank"/>

// Renders the TEXT of the project's l2/molecules/skill.ts (level 1). Pure — the step reads the
// already-written index.defs.ts of every group in this run and hands their data here; nothing is
// re-derived from level 2 (the group order and molecule lists are computed once, by the caller).
//
// ⚠️ ORDER: matched groups come out of syDiscoverGroups alphabetical by folder, and this module keeps
// that order for BOTH the `groups` array and the markdown sections. The first guess was skills/index.ts
// order — 4 of the 6 pilot groups looked like they matched it — and E5's regeneration falsified it: the
// seeded skill.ts lists 'groupViewTable' before 'groupEnterDate', the OPPOSITE of their skills/index.ts
// order. Alphabetical is simple, deterministic, and matches what the seed actually does once the false
// pattern is set aside. Group -> project only runs after EVERY group's index.defs.ts of this batch is
// written (analysis §12.2) — enforced by the step, not here; this module only renders what it is given.
//
// ⚠️ PURPOSE TEXT: the full skills/index.ts `description`, untruncated — see syRenderDefs.ts's header
// and flow.json `decisions.purposeText` for why the seed's shorter text is not reproduced here.

export interface SyRenderSkillGroup {
  canonical: string;
  folder: string;
  purpose: string;
  /** Short tag names ('ml-card-selector', no group prefix), in the same order as this group's molecules[]. */
  moleculeShortTags: string[];
}

export interface SyRenderSkillInput {
  project: number;
  groups: SyRenderSkillGroup[];
  generatedAt: string;
}

export function syRenderProjectSkill(input: SyRenderSkillInput): string {
  const lines: string[] = [];
  lines.push(`/// <mls fileReference="_${input.project}_/l2/molecules/skill.ts" enhancement="_blank"/>`);
  lines.push('');
  lines.push('// Do not change – automatically generated code.');
  lines.push(`// Generated by agentSyncMoleculeCatalog on ${input.generatedAt}.`);
  lines.push('');
  lines.push(`export const project = '${input.project}';`);
  lines.push('');
  lines.push('// Este projeto não tem tema local.');
  lines.push('export const theme = null;');
  lines.push('');
  lines.push('export const groups = [');
  for (const group of input.groups) {
    lines.push(`    { name: '${group.canonical}', molecules: ${group.moleculeShortTags.length}, indexDefs: '/_${input.project}_/l2/molecules/${group.folder}/index.defs' },`);
  }
  lines.push('];');
  lines.push('');
  lines.push(`export const skill = \`${renderProjectSkillMarkdown(input)}\`;`);
  lines.push('');
  return lines.join('\n');
}

function renderProjectSkillMarkdown(input: SyRenderSkillInput): string {
  const parts: string[] = [];
  parts.push(`# Molecules — catálogo do projeto mls-${input.project} (${input.groups.length} grupo${input.groups.length === 1 ? '' : 's'})`);
  parts.push('');
  parts.push('## Como consumir (em etapas, para não estourar o prompt)');
  parts.push('');
  parts.push(
    '1. Leia ESTE arquivo e escolha os GRUPOS que a página precisa. A lista de moléculas de cada grupo está abaixo para isso: se o nome de uma molécula corresponde ao que a região precisa, o grupo dela é o caminho.',
  );
  parts.push('2. Para cada grupo escolhido, leia o catálogo do grupo (index.defs) e escolha a MOLÉCULA pela descrição completa.');
  parts.push('3. Antes de escrever marcação, leia o contrato de uso do grupo (o index.defs do grupo aponta para ele).');
  parts.push('');
  parts.push('Se a página precisa de algo que NENHUM grupo abaixo cobre, responda que não há molécula disponível para aquela região — NUNCA invente uma tag.');
  parts.push('');
  parts.push('## Grupos disponíveis');
  parts.push('');
  for (const group of input.groups) {
    parts.push(`### ${group.canonical} (${group.moleculeShortTags.length} moléculas)`);
    parts.push(group.purpose);
    parts.push(`Moléculas: ${group.moleculeShortTags.join(', ')}`);
    parts.push('');
  }
  parts.push('Este projeto não tem tema local.');
  return `${parts.join('\n')}\n`;
}
