/// <mls fileReference="_102020_/l2/aura/molecules/agentSyncMoleculeCatalog/helpers/syRenderDefs.ts" enhancement="_blank"/>

// Renders the TEXT of one group's index.defs.ts (level 2). Pure — takes already-extracted data in,
// returns a string; the step writes it to the stor.
//
// ⚠️ THE FORMAT IS NOT INVENTED HERE — it is anchored on the 6 groups seeded by hand for the
// agentChooseMolecules pilot (todo §4, "os 7 arquivos semeados SÃO a especificação"). E5's acceptance
// is regenerating those 6 groups from their real source files and diffing against the seed: a
// structural difference is a bug in this renderer; a content difference (e.g. the group's `purpose`
// text, which the manually-maintained skills/index.ts has kept editing since the seed was taken) is
// expected and is not "fixed" here to force a match — see flow.json `decisions.purposeText`.

import { SyMoleculeEntry, SyScenario } from '/_102020_/l2/aura/molecules/agentSyncMoleculeCatalog/helpers/syTypes.js';

export interface SyRenderDefsInput {
  project: number;
  groupCanonical: string;
  groupFolder: string;
  usageContract: string;
  purpose: string;
  /** Already sorted (alphabetically, by tag) and axis-reduced — this module renders, it does not decide order. */
  molecules: SyMoleculeEntry[];
  scenarios: SyScenario[];
  /** ISO timestamp of this run, stamped in the generated-by comment. */
  generatedAt: string;
}

/**
 * The whole file: one line, `<molecules--<groupfolder>--index-<project>>` opened and closed
 * (todo §4.3, measured 81–107 bytes across the seeded groups). No trailing newline — matches the
 * seeded files exactly, which is worth keeping since this file is never hand-edited.
 */
export function syRenderIndexHtml(groupFolder: string, project: number): string {
  const tag = `molecules--${groupFolder}--index-${project}`;
  return `<${tag}></${tag}>`;
}

export function syRenderIndexDefs(input: SyRenderDefsInput): string {
  const lines: string[] = [];
  lines.push(`/// <mls fileReference="_${input.project}_/l2/molecules/${input.groupFolder}/index.defs.ts" enhancement="_blank"/>`);
  lines.push('');
  lines.push('// Do not change – automatically generated code.');
  lines.push(`// Generated by agentSyncMoleculeCatalog on ${input.generatedAt}.`);
  lines.push('');
  lines.push(`export const group = '${escapeSingleQuoted(input.groupCanonical)}';`);
  lines.push('');
  lines.push('// Contrato do grupo (slots, propriedades, eventos, exemplos) — referenciado, nunca');
  lines.push('// copiado (contrato é manual: decisão de 17/08). Leia ANTES de escrever marcação.');
  lines.push(`export const usageContract = '${escapeSingleQuoted(input.usageContract)}';`);
  lines.push('');
  lines.push('// Lista estruturada, para consumo determinístico (gates, lints).');
  lines.push('// layout = eixos do layoutConfig que VARIAM entre os irmãos deste grupo.');
  lines.push('export const molecules = [');
  for (const molecule of input.molecules) lines.push(`    ${renderMoleculeEntry(molecule)}`);
  lines.push('];');
  lines.push('');
  lines.push('// Tabela "Quick reference" (cenário -> recomendadas). Editorial: não é derivada do catálogo.');
  lines.push('export const scenarios = [');
  for (const scenario of input.scenarios) lines.push(`    ${renderScenarioEntry(scenario)}`);
  lines.push('];');
  lines.push('');
  lines.push(`export const skill = \`${renderSkillMarkdown(input)}\`;`);
  lines.push('');
  return lines.join('\n');
}

function renderMoleculeEntry(molecule: SyMoleculeEntry): string {
  const parts = [`tag: '${escapeSingleQuoted(molecule.tag)}'`];
  const axes = molecule.layout ? Object.entries(molecule.layout) : [];
  if (axes.length) {
    parts.push(`layout: { ${axes.map(([axis, value]) => `${axis}: '${escapeSingleQuoted(value)}'`).join(', ')} }`);
  }
  parts.push(molecule.defsRef ? `defs: '${escapeSingleQuoted(molecule.defsRef)}'` : 'defs: null /* ⚠ sem .defs.ts — fora de contrato */');
  return `{ ${parts.join(', ')} },`;
}

function renderScenarioEntry(scenario: SyScenario): string {
  const recommended = scenario.recommended.map(tag => `'${escapeSingleQuoted(tag)}'`).join(', ');
  return `{ scenario: '${escapeSingleQuoted(scenario.scenario)}', recommended: [${recommended}] },`;
}

function renderSkillMarkdown(input: SyRenderDefsInput): string {
  const parts: string[] = [];
  parts.push(`# ${input.groupCanonical} — moléculas disponíveis (mls-${input.project})`);
  parts.push('');
  parts.push(`Objetivo do grupo: ${input.purpose}`);
  parts.push('');
  parts.push('## Como escolher');
  parts.push('');
  parts.push('1. Se o cenário da página bate com um da tabela abaixo, comece pelas recomendadas.');
  parts.push('2. Desempate pelo layout e pela descrição completa de cada molécula.');
  parts.push('3. Antes de escrever a marcação, leia o contrato de uso do grupo (usageContract).');
  parts.push('   A tag deve ser copiada EXATAMENTE como está aqui.');
  parts.push('');
  parts.push('## Cenários (quick reference)');
  parts.push('');
  parts.push('| cenário | recomendadas |');
  parts.push('|---|---|');
  for (const scenario of input.scenarios) {
    const shortTags = scenario.recommended.map(shortTagOf).join(', ');
    parts.push(`| ${scenario.scenario} | ${shortTags || '—'} |`);
  }
  parts.push('');
  parts.push(`## Moléculas (${input.molecules.length})`);
  parts.push('');
  for (const molecule of input.molecules) {
    if (!molecule.defsRef || !molecule.objective) {
      parts.push(`- **${molecule.tag}** — ⚠ fora de contrato: sem .defs.ts (objetivo indisponível; leia o arquivo da molécula antes de usar).`);
      continue;
    }
    const axes = molecule.layout ? Object.entries(molecule.layout) : [];
    const layoutSegment = axes.length ? ` · ${axes.map(([axis, value]) => `${axis}: ${value}`).join(', ')}` : '';
    parts.push(`- **${molecule.tag}**${layoutSegment} — ${molecule.objective}`);
  }
  return `${parts.join('\n')}\n`;
}

/** 'groupenternumber--ml-number-input' -> 'ml-number-input', for the markdown table only. */
function shortTagOf(tag: string): string {
  const at = tag.indexOf('--');
  return at >= 0 ? tag.slice(at + 2) : tag;
}

function escapeSingleQuoted(text: string): string {
  return (text || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
