/// <mls fileReference="_102020_/l2/aura/molecules/agentSyncMoleculeCatalog/helpers/syRenderSkill.ts" enhancement="_blank"/>

// Renders the TEXT of the project's l2/molecules/skill.ts (level 1). Pure — the step reads the
// already-written index.defs.ts of every group in this run and hands their data here; nothing is
// re-derived from level 2 (the group order and molecule lists are computed once, by the caller).
//
// ⚠️ ORDER: matched groups come out of syDiscoverGroups alphabetical by folder, and this module keeps
// that order for BOTH the `groups` array and the markdown sections. The first guess was skills/index.ts
// order — 4 of the 6 pilot groups looked like they matched it — and E5's regeneration falsified it: the
// seeded skill.ts lists 'groupViewTable' before 'groupEnterDate', the OPPOSITE of their skills/index.ts
// order. Alphabetical is simple, deterministic, and matches what the seed actually does once the false
// pattern is set aside. Group -> project only runs after EVERY group's index.defs.ts of this batch is
// written (analysis §12.2) — enforced by the step, not here; this module only renders what it is given.
//
// ⚠️ PURPOSE TEXT: the full skills/index.ts `description`, untruncated — see syRenderDefs.ts's header
// and flow.json `decisions.purposeText` for why the seed's shorter text is not reproduced here.

import { syEscapeTemplateLiteral } from '/_102020_/l2/aura/molecules/agentSyncMoleculeCatalog/helpers/syTemplateText.js';

export interface SyRenderSkillGroup {
  canonical: string;
  folder: string;
  purpose: string;
  /** Short tag names ('ml-card-selector', no group prefix), in the same order as this group's molecules[]. */
  moleculeShortTags: string[];
}

export interface SyRenderSkillInput {
  project: number;
  groups: SyRenderSkillGroup[];
  generatedAt: string;
}

export function syRenderProjectSkill(input: SyRenderSkillInput): string {
  const lines: string[] = [];
  lines.push(`/// <mls fileReference="_${input.project}_/l2/molecules/skill.ts" enhancement="_blank"/>`);
  lines.push('');
  lines.push('// Do not change – automatically generated code.');
  lines.push(`// Generated by agentSyncMoleculeCatalog on ${input.generatedAt}.`);
  lines.push('');
  lines.push(`export const project = '${input.project}';`);
  lines.push('');
  lines.push('// This project has no local theme.');
  lines.push('export const theme = null;');
  lines.push('');
  lines.push('export const groups = [');
  for (const group of input.groups) {
    lines.push(`    { name: '${group.canonical}', molecules: ${group.moleculeShortTags.length}, indexDefs: '/_${input.project}_/l2/molecules/${group.folder}/index.defs' },`);
  }
  lines.push('];');
  lines.push('');
  // Escaped: the prose comes from skills/index.ts, and a backtick in it (markdown inline code, e.g.
  // "via the `variant` property") would close this template literal early — measured 2026-08-26.
  lines.push(`export const skill = \`${syEscapeTemplateLiteral(renderProjectSkillMarkdown(input))}\`;`);
  lines.push('');
  return lines.join('\n');
}

function renderProjectSkillMarkdown(input: SyRenderSkillInput): string {
  const parts: string[] = [];
  parts.push(`# Molecules — catalog of project mls-${input.project} (${input.groups.length} group${input.groups.length === 1 ? '' : 's'})`);
  parts.push('');
  parts.push('## How to consume it (one level at a time, so the prompt stays small)');
  parts.push('');
  parts.push(
    '1. Read THIS file and choose the GROUPS the page needs. Each group lists its molecules below for exactly that: if a molecule name matches what the region needs, its group is the way in.',
  );
  parts.push('2. For each chosen group, read the group catalog (index.defs) and choose the MOLECULE by its full description.');
  parts.push('3. Before writing markup, read the group usage contract (the group index.defs points at it).');
  parts.push('');
  parts.push('If the page needs something NO group below covers, answer that there is no molecule available for that region — NEVER invent a tag.');
  parts.push('');
  parts.push('## Available groups');
  parts.push('');
  for (const group of input.groups) {
    parts.push(`### ${group.canonical} (${group.moleculeShortTags.length} molecule${group.moleculeShortTags.length === 1 ? '' : 's'})`);
    parts.push(group.purpose);
    parts.push(`Molecules: ${group.moleculeShortTags.join(', ')}`);
    parts.push('');
  }
  parts.push('This project has no local theme.');
  return `${parts.join('\n')}\n`;
}
