/// <mls fileReference="_102020_/l2/agentImplementsDesignSystem2/agentSelectGroups2.ts" enhancement="_102027_/l2/enhancementAgent"/>

// Group A executor (Fase B + C). One per page (spawned by the orchestrator).
// beforePromptStep → prompt (rendered .ts + raw definition + groups).
// afterPromptStep  → resolve molecules (deterministic) + write the NEW defs into
//                    page{layout}{ds}/<page>.defs.ts (with moleculeAssignments + usagePaths).
//
// No beforePromptImplicit: this agent is never invoked directly, only as a planned step.

import { IAgentAsync, IAgentMeta } from '/_102027_/l2/aiAgentBase.js';
import { buildWorkItem } from '/_102020_/l2/dsMatch/derivePaths.js';
import { buildGroupList } from '/_102020_/l2/dsMatch/groupCatalog.js';
import { loadPageSource, loadPageDefinitionText, buildAgent1HumanPrompt, validateAgent1Output } from '/_102020_/l2/dsMatch/agent1.js';
import { readDsRules } from '/_102020_/l2/dsMatch/readDsRules.js';
import { buildMoleculeCatalog } from '/_102020_/l2/dsMatch/buildMoleculeCatalog.js';
import { resolveMolecules, assignMoleculesToPage, collectUsedGroups, collectUsagePaths } from '/_102020_/l2/dsMatch/resolveMolecules.js';
import { parseStepArgs, mkCompleted, mkFail, saveFile } from '/_102020_/l2/agentImplementsDesignSystem2/planning.js';

export function createAgent(): IAgentAsync {
  return {
    agentName: 'agentSelectGroups2',
    agentProject: 102020,
    agentFolder: 'agentImplementsDesignSystem2',
    agentDescription: 'Select molecule groups per organism and write the new page defs (Fase B+C)',
    visibility: 'private',
    beforePromptStep,
    afterPromptStep,
  };
}

async function beforePromptStep(
  agent: IAgentMeta,
  context: mls.msg.ExecutionContext,
  parentStep: mls.msg.AIAgentStep,
  step: mls.msg.AIAgentStep,
  hookSequential: number,
  args?: string,
): Promise<mls.msg.AgentIntent[]> {

  const a = parseStepArgs(args ?? step.prompt);
  const project = mls.actualProject || 0;
  const item = buildWorkItem(project, a.module, a.layout, a.ds, a.page!, a.device);

  const pageSource = await loadPageSource(item.tsOrigem);
  const definitionText = await loadPageDefinitionText(item.tsOrigem);
  const groups = await buildGroupList();
  const humanPrompt = buildAgent1HumanPrompt(item.tsOrigem, pageSource, definitionText, groups);

  const continueParallel: mls.msg.AgentIntentPromptReady = {
    type: 'prompt_ready',
    args: args ?? step.prompt,
    messageId: context.message.orderAt,
    threadId: context.message.threadId,
    taskId: context.task?.PK || '',
    hookSequential,
    parentStepId: parentStep.stepId,
    humanPrompt,
    systemPrompt: system1,
  };

  return [continueParallel];
}

async function afterPromptStep(
  agent: IAgentMeta,
  context: mls.msg.ExecutionContext,
  parentStep: mls.msg.AIAgentStep,
  step: mls.msg.AIAgentStep,
  hookSequential: number,
): Promise<mls.msg.AgentIntent[]> {

  try {
    const payload = step.interaction?.payload?.[0];
    if (payload?.type !== 'flexible' || !payload.result) throw new Error(`invalid payload: ${JSON.stringify(payload)}`);

    const a = parseStepArgs(step.prompt);
    const project = mls.actualProject || 0;
    const item = buildWorkItem(project, a.module, a.layout, a.ds, a.page!, a.device);

    const dsRules = await readDsRules(project, a.ds);
    const catalog = await buildMoleculeCatalog();
    const groups = await buildGroupList();
    const validGroups = new Set(groups.map(g => g.group));

    const validated = validateAgent1Output(payload.result, validGroups, item.defsDestino);
    const resolved = resolveMolecules(dsRules, catalog, collectUsedGroups([validated]));
    const assignment = assignMoleculesToPage(validated, resolved);
    const usagePaths = collectUsagePaths(assignment, resolved);

    if (!context.isTest) await saveFile(item.defsDestino, buildNovoDefs(item.defsDestino, assignment.organisms, usagePaths));

    return [mkCompleted(context, parentStep, step, hookSequential)];
  } catch (error) {
    return [mkFail(context, parentStep, step, hookSequential, `[agentSelectGroups2] ${error instanceof Error ? error.message : String(error)}`)];
  }
}

/** The intermediate "new defs": resolved molecule assignments for agentGenDefs2 to weave. */
function buildNovoDefs(defsRef: string, organisms: unknown, usagePaths: string[]): string {
  const cleanRef = defsRef.startsWith('/') ? defsRef.slice(1) : defsRef;
  return [
    `/// <mls fileReference="${cleanRef}" enhancement="_blank"/>`,
    '',
    '// Generated by agentSelectGroups2 (Fase B+C). Molecule choices are resolved',
    '// deterministically for this design system. Consumed by agentGenDefs2 (Fase E).',
    '',
    `export const moleculeAssignments = ${JSON.stringify(organisms, null, 2)} as const;`,
    '',
    `export const usagePaths = ${JSON.stringify(usagePaths, null, 2)} as const;`,
    '',
  ].join('\n');
}

const system1 = `
<!-- modelType: codeinstruct -->

You must return ONLY a valid JSON object. No preamble, no explanation, no markdown
fences. Start your response with { and end with }

## Task
You are given the page's RENDERED source (a Lit component with HTML + Tailwind) and the
page definition (sections, organisms, fields). For each organism, decide which molecule
GROUPS are needed to replace the hand-built UI elements that belong to it. Base the
decision on the ACTUAL elements in the rendered HTML, mapped to the organism they sit in.
Use the organismName values from the page definition.

## Rules
- Map a group only when its purpose DIRECTLY and OBVIOUSLY matches a real UI element.
- An organism may need several groups, one, or none. Shorter accurate beats longer wrong.
- Choose group names EXACTLY as listed (camelCase). Never invent a group; omit if none fits.
- Decide GROUPS only — never a specific variant/molecule (that is deterministic, done later).

## Output format
[[OutputSection]]
`;

//#region OutputSection
export type Output = {
  type: 'flexible';
  result: {
    perOrganism: Array<{ organismName: string; groups: string[] }>;
  };
};
//#endregion
