/// <mls fileReference="_102020_/l2/agentDefsL2/skills/genD2SharedTs.ts" enhancement="_blank"/>

export const skill = `# Generate one D2 shared TypeScript class

Generate only the headless shared behavior described by the supplied D2 definition. Export the class named by baseClassName, extend StateLitElement, and do not register a custom element or implement render(). Never invent a route, state, action, field, permission, message, layout, section or i18n catalog.

Use the contract .defs.ts named by contractRef.defPath as the only source of route constants and Input/Output types. Import its route constants as values and its used interfaces/types with import type; the generated import uses the corresponding .js specifier. Do not require or guess a contracts/*.ts file.

Use only APIs present in the expanded _102029_.d.ts context: StateLitElement from stateLitElement.js; execBff and BffClientOptions from bffClient.js; getState, setState, subscribe and unsubscribe from collabState.js; and runBlockingUiAction from interactionRuntime.js. execBff(routeConst, params, options) returns { ok, data, error }. Queries use mode silent; commands run through runBlockingUiAction with mode blocking. Store response.data only after ok, and store the real error otherwise.

Expose one typed public property for every definition state using its exact memberName, initialized from defaultValue. Array outputs remain arrays. State valueSet values remain literal unions. Treat dtoPath as the exact path inside the call's Input DTO and ontologyRef as provenance only; never send the entity prefix from ontologyRef. Build nested request objects by placing each state value at its dtoPath in the contract input type. Omit optional null, undefined or empty values; block an absent required value with an actionable error. States whose source is selectedEntity, routeParam or session are contextual inputs: they may be read and sent, but must not become editable setters. Generate stateSetter methods only for declared editable states and use setState with the exact stateKey. For each snapshotPreconditions item, capture valuePath from the source result row whose identityPath matches selectedIdentityStateKey when selection is made. A changed or cleared selection clears the old token before capturing the new row; a refresh for the same selection must not replace the captured edit token. If the required token is null, missing or invalid, do not call execBff: retain all edit states and publish an actionable error. Never fetch or fabricate a token while sending and never retry a conflict automatically.

Generate every declared query and command action using its exact methodName, update its exact loading/success/error states, write its declared output states, honor confirmations and refreshActionIds, and never silently stub a call. Preserve operationBinding actorRef, grants, authorities, transition payload, ruleRefs and sourceHashes as traceable action metadata; use them to explain the action and reflect visibility, but never evaluate authorization in the browser. Generate initialLoads exactly as declared, with no fabricated route/query IDs. Generate every scenario entry method using its exact methodName and declared value; check each precondition before entering or invoking a scenario and preserve actionable error feedback. dataBindings and inputStateKeys are the closed mapping from actions to routes, DTO paths and result states.

Use declared title, description and enumOptions labels; valueSet contains the actual submitted codes. Preserve every operationBindings entry by actor, including the scenario metadata. coverage is the authoritative organism/content inventory, with stable IDs, sourceIndex, raw source and available scenario/capability refs; it does not add endpoints or executable expressions from content prose.

Selection actions use their declared selection sourceActionId, resultStateKey and identityPath. Accept only an identity present in that authorised query result; copy that real identity to stateKey and capture all associated snapshotPreconditions in the same selection operation. Clearing selection clears snapshots. Re-selecting the same identity or refreshing its rows leaves the current edit token unchanged. Do not fabricate a picker query from ontology references.

Generate the declared setScenario setter with the scenary literal union; it must resolve the requested declared scenario and check its preconditions before updating scenary. Every entry method delegates to the same setter. The setter enters the scenario without submitting its command. Commands check their own required inputs again on submission.

Set action status to loading synchronously before awaiting a command, reject a duplicate while that action is loading, and clear its previous error. Publish every feedback/output change with the exact state key and update the corresponding public property. Queries use pageStatus loading, empty for an empty result, success otherwise, and error on failure. Preserve input values on all failures, including conflict. Keep the complete response.error envelope (code/message/details) in the error state; presentation reads its message. Refresh only after response.ok, invoke only declared refreshActionIds whose real required context is available, and never replace the edit snapshot during refresh. Catch thrown runtime errors and set the action error/status; do not leave loading stuck. All user-facing fallback feedback is i18n with default en.

In connectedCallback call super, hydrate/subscribe declared state keys, then execute initialLoads. In disconnectedCallback unsubscribe the same keys before super. Implement handleIcaStateChange so subscribed values update their matching public properties and request an update. Its first statement must be "if (value === undefined) return;": initial StateLitElement notifications may have no store value and must not overwrite locally initialized defaults. Apply all defined values, including null, false and zero; do not use a truthiness or nullish guard. Use only memberName and methodName values carried by the definition; do not normalize names independently. If any generated state, setter, action or scenario member collides with another member or an inherited StateLitElement/LitElement member, fail instead of suffixing, overwriting or dropping it.

The generated class is the public surface consumed by page11: its state properties and action methods must remain public and typed. Emit no HTML, CSS, customElement, render method, layoutRef, translations or endpoint not present in the definition and contract context.`;
