/// <mls fileReference="_102020_/l2/agentMaterializeL2v3/steps/contracts30/run.ts" enhancement="_blank"/>

import { readJson, writeJson, type Ns5FileInfo } from '/_102035_/l2/solution/fs.js';
import { sha256Text } from '/_102020_/l2/helpers/hash.js';
import { compileM3FinalSources, type M3CompileProof, type M3FinalSource } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3CompileProof.js';
import { buildM3Receipt, m3ReceiptFresh, m3ReceiptPath, readM3Sources, type M3Reader } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3Receipt.js';
import type { M3RunIdentity } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3Invocation.js';
import { failM3Step, m3ErrorMessage, productionFailurePort, type M3FailurePort } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3StepFailure.js';
import { getContentByMlsPath, saveArtifactTextByMlsPath } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3Studio.js';
import { m3TraceFileInfo } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3Trace.js';
import type { M3StepResult } from '/_102020_/l2/agentMaterializeL2v3/steps/entry10/run.js';
import type { M3Input, M3InputRequest } from '/_102020_/l2/agentMaterializeL2v3/steps/input20/run.js';

export const M3_CONTRACT_MARKER = '// Generated by agentMaterializeL2v3 (contracts30)';

export interface M3ContractPageTrace {
  pageId: string;
  outputPath: string;
  status: 'written' | 'unchanged' | 'reused' | 'failed';
  reason?: string;
  compile?: M3CompileProof;
}

export interface M3ContractsPort {
  readInput(): Promise<M3Input | null>;
  /** Reads by mls path (`_<p>_/l2/...`); null = absent. Also the receipt reader. */
  read: M3Reader;
  writeTs(mlsPath: string, source: string): Promise<boolean>;
  writeText(mlsPath: string, content: string): Promise<boolean>;
  compile(sources: M3FinalSource[], hashes: Map<string, string>): Promise<M3CompileProof[]>;
  writeJson(info: Ns5FileInfo, value: unknown): Promise<unknown>;
  failure: M3FailurePort;
}

export function productionContractsPort(identity: { project: number; module: string; runDir: string }): M3ContractsPort {
  return {
    readInput: () => readJson<M3Input>(m3TraceFileInfo(identity.project, identity.module, identity.runDir, 'input')),
    read: getContentByMlsPath,
    // D-011: write without an editor model or compile; m3CompileProof is the only compile.
    writeTs: saveArtifactTextByMlsPath,
    writeText: saveArtifactTextByMlsPath,
    compile: (sources, hashes) => compileM3FinalSources(identity.project, sources, hashes),
    writeJson,
    failure: productionFailurePort(identity.project, identity.module, identity.runDir),
  };
}

/** Pure. One typed function per request over execBff (D-008). */
export function renderM3ContractClient(project: number, module: string, pageId: string, requests: readonly M3InputRequest[]): string {
  const contracts = `${pageId.charAt(0).toUpperCase()}${pageId.slice(1)}Contracts`;
  const functions = requests.map(({ requestId, route }) => [
    `export function ${requestId}(`,
    `  input: Input<'${route}'>,`,
    '  options?: BffClientOptions,',
    `): Promise<BffClientResponse<Output<'${route}'>>> {`,
    `  return execBff<Output<'${route}'>>('${route}', input, options);`,
    '}',
  ].join('\n'));
  return [
    `/// <mls fileReference="_${project}_/l2/${module}/web/contracts/${pageId}.ts" enhancement="_blank"/>`,
    '',
    `${M3_CONTRACT_MARKER} from ${pageId}.defs.ts. Do not edit.`,
    '',
    "import { execBff, type BffClientOptions, type BffClientResponse } from '/_102029_/l2/bffClient.js';",
    `import type { ${contracts} } from '/_${project}_/l2/${module}/web/contracts/${pageId}.defs.js';`,
    '',
    `type Route = keyof ${contracts};`,
    `type Input<R extends Route> = ${contracts}[R]['input'];`,
    `type Output<R extends Route> = ${contracts}[R]['output'];`,
    '',
    functions.join('\n\n'),
  ].join('\n') + '\n';
}

export async function executeM3Contracts(port: M3ContractsPort, identity: M3RunIdentity & { runDir: string }): Promise<M3StepResult & { pages?: M3ContractPageTrace[] }> {
  const { project, module, runDir } = identity;
  const fail = async (reason: string): Promise<M3StepResult> => ({ status: 'failed', reason: await failM3Step(port.failure, { module, runDir, stepId: 'contracts30' }, reason) });
  let input: M3Input | null;
  try { input = await port.readInput(); } catch (error) { return fail(`M3_INPUT_MISSING: ${m3ErrorMessage(error)}`); }
  if (!input) return fail(`M3_INPUT_MISSING: input.json of ${runDir}`);

  const pages: M3ContractPageTrace[] = [];
  for (const page of input.pages) {
    const outputPath = `_${project}_/l2/${module}/web/contracts/${page.pageId}.ts`;
    const trace: M3ContractPageTrace = { pageId: page.pageId, outputPath, status: 'failed' };
    pages.push(trace);
    try {
      const defPath = `_${project}_/${page.defs.contract.path}`;
      const sharedPath = `_${project}_/${page.defs.shared.path}`;
      const source = renderM3ContractClient(project, module, page.pageId, page.requests);
      const exported = [...source.matchAll(/^export function (\w+)\(/gmu)].map(match => match[1]);
      if (JSON.stringify(exported) !== JSON.stringify(page.requests.map(item => item.requestId))) {
        throw new Error(`M3_CONTRACT_SHAPE: ${page.pageId} exports [${exported.join(',')}] expected [${page.requests.map(item => item.requestId).join(',')}]`);
      }
      const existing = await port.read(outputPath);
      if (existing !== null && !existing.includes(M3_CONTRACT_MARKER)) throw new Error(`M3_FOREIGN_FILE: ${outputPath}`);
      if (await m3ReceiptFresh({ defPath, outputPath, sourceRefs: [defPath, sharedPath], project, read: port.read })) {
        trace.status = 'reused';
        continue;
      }
      const needsWrite = existing !== source;
      if (needsWrite && !await port.writeTs(outputPath, source)) throw new Error(`M3_WRITE_FAILED: ${outputPath}`);
      const compilePath = `l2/${module}/web/contracts/${page.pageId}.ts`;
      const [proof] = await port.compile(
        [{ pageId: page.pageId, kind: 'contract', path: compilePath, source }],
        new Map([[compilePath, await sha256Text(source)]]),
      );
      trace.compile = proof;
      if (!proof || proof.status !== 'passed') throw new Error(`M3_CONTRACT_COMPILE_FAILED: ${proof ? proof.diagnostics.join('; ') : 'no compile result'}`);
      const receipt = await buildM3Receipt({
        defPath, outputPath, sources: await readM3Sources([defPath, sharedPath], project, port.read), skills: [], context: [], output: source, project, read: port.read,
      });
      if (!await port.writeText(m3ReceiptPath(outputPath), `${JSON.stringify(receipt, null, 2)}\n`)) throw new Error(`M3_WRITE_FAILED: ${m3ReceiptPath(outputPath)}`);
      trace.status = needsWrite ? 'written' : 'unchanged';
    } catch (error) {
      trace.status = 'failed';
      trace.reason = m3ErrorMessage(error);
    }
  }

  await port.writeJson(m3TraceFileInfo(project, module, runDir, 'contracts30'), { pages });
  const failed = pages.filter(item => item.status === 'failed');
  if (failed.length) return { ...(await fail(failed.map(item => `${item.pageId}: ${item.reason}`).join(' | '))), pages };
  const written = pages.filter(item => item.status === 'written').length;
  return { status: 'completed', summary: `contracts30 wrote ${written} and reused ${pages.length - written}`, pages };
}
