/// <mls fileReference="_102020_/l2/agentMaterializeL2v3/steps/contracts30/run.test.ts" enhancement="_blank"/>

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { sha256Text } from '/_102020_/l2/helpers/hash.js';
import type { M3CompileProof } from '/_102020_/l2/agentMaterializeL2v3/helpers/m3CompileProof.js';
import { M3_CONTRACT_MARKER, executeM3Contracts, renderM3ContractClient, type M3ContractsPort } from '/_102020_/l2/agentMaterializeL2v3/steps/contracts30/run.js';
import { executeM3Input, type M3Input, type M3InputPort } from '/_102020_/l2/agentMaterializeL2v3/steps/input20/run.js';
import { CONTROLE_ESTOQUE_DEFS, CONTROLE_ESTOQUE_OWNERSHIP, CONTROLE_ESTOQUE_REPORT } from '/_102020_/l2/agentMaterializeL2v3/steps/input20/fixtures/controleEstoqueFixture.js';

const PROJECT = 102047;
const MODULE = 'controleEstoque';
const identity = { project: PROJECT, module: MODULE, pages: null, devices: ['desktop' as const, 'mobile' as const], runDir: 'run_20261001143205' };
const outPath = (page: string) => `_${PROJECT}_/l2/${MODULE}/web/contracts/${page}.ts`;
const mls = (path: string) => `_${PROJECT}_/${path}`;

const GOLDEN_PRODUTOS = `/// <mls fileReference="_102047_/l2/controleEstoque/web/contracts/produtos.ts" enhancement="_blank"/>

// Generated by agentMaterializeL2v3 (contracts30) from produtos.defs.ts. Do not edit.

import { execBff, type BffClientOptions, type BffClientResponse } from '/_102029_/l2/bffClient.js';
import type { ProdutosContracts } from '/_102047_/l2/controleEstoque/web/contracts/produtos.defs.js';

type Route = keyof ProdutosContracts;
type Input<R extends Route> = ProdutosContracts[R]['input'];
type Output<R extends Route> = ProdutosContracts[R]['output'];

export function load(
  input: Input<'controleEstoque.produtos.load'>,
  options?: BffClientOptions,
): Promise<BffClientResponse<Output<'controleEstoque.produtos.load'>>> {
  return execBff<Output<'controleEstoque.produtos.load'>>('controleEstoque.produtos.load', input, options);
}

export function cadastrarProduto(
  input: Input<'controleEstoque.produtos.cadastrarProduto'>,
  options?: BffClientOptions,
): Promise<BffClientResponse<Output<'controleEstoque.produtos.cadastrarProduto'>>> {
  return execBff<Output<'controleEstoque.produtos.cadastrarProduto'>>('controleEstoque.produtos.cadastrarProduto', input, options);
}
`;

const GOLDEN_MOVIMENTACOES = `/// <mls fileReference="_102047_/l2/controleEstoque/web/contracts/movimentacoes.ts" enhancement="_blank"/>

// Generated by agentMaterializeL2v3 (contracts30) from movimentacoes.defs.ts. Do not edit.

import { execBff, type BffClientOptions, type BffClientResponse } from '/_102029_/l2/bffClient.js';
import type { MovimentacoesContracts } from '/_102047_/l2/controleEstoque/web/contracts/movimentacoes.defs.js';

type Route = keyof MovimentacoesContracts;
type Input<R extends Route> = MovimentacoesContracts[R]['input'];
type Output<R extends Route> = MovimentacoesContracts[R]['output'];

export function load(
  input: Input<'controleEstoque.movimentacoes.load'>,
  options?: BffClientOptions,
): Promise<BffClientResponse<Output<'controleEstoque.movimentacoes.load'>>> {
  return execBff<Output<'controleEstoque.movimentacoes.load'>>('controleEstoque.movimentacoes.load', input, options);
}

export function registrarMovimentacao(
  input: Input<'controleEstoque.movimentacoes.registrarMovimentacao'>,
  options?: BffClientOptions,
): Promise<BffClientResponse<Output<'controleEstoque.movimentacoes.registrarMovimentacao'>>> {
  return execBff<Output<'controleEstoque.movimentacoes.registrarMovimentacao'>>('controleEstoque.movimentacoes.registrarMovimentacao', input, options);
}
`;

/** input.json produced by the real input20 on the real fixture. */
async function realInput(): Promise<M3Input> {
  const files: Record<string, string> = {
    ...CONTROLE_ESTOQUE_DEFS,
    [`l2/${MODULE}/pipeline/agentDefsL2/finalize80/report.json`]: CONTROLE_ESTOQUE_REPORT,
    [`l2/${MODULE}/pipeline/agentDefsL2/finalize80/ownership.json`]: CONTROLE_ESTOQUE_OWNERSHIP,
  };
  const port: M3InputPort = {
    readText: async path => files[path] ?? null,
    readJson: async <T>(path: string) => JSON.parse(files[path]) as T,
    writeJson: async () => undefined,
    failure: { recordDegradation: async () => undefined, saveSummary: async () => null, readRun: async () => null, now: () => new Date() },
  };
  return (await executeM3Input(port, identity) as { input: M3Input }).input;
}

/** In-memory stor that also serves the .defs and bffClient sources, so the real receipt code runs. */
function makePort(input: M3Input | null, initial: Record<string, string> = {}, compileOver?: (sources: any[]) => M3CompileProof[]) {
  const stor: Record<string, string> = { ...initial, [mls('l2/controleEstoque/web/contracts/produtos.defs.ts')]: '', [mls('l2/controleEstoque/web/contracts/movimentacoes.defs.ts')]: '' };
  for (const [path, content] of Object.entries(CONTROLE_ESTOQUE_DEFS)) stor[mls(path)] = content;
  stor['_102029_/l2/bffClient.ts'] = 'export const execBff = 1;\n';
  Object.assign(stor, initial);
  const calls: string[] = [];
  const traces: any[] = [];
  const failures: string[] = [];
  const port: M3ContractsPort = {
    readInput: async () => input,
    read: async path => stor[path] ?? null,
    writeTs: async (path, source) => { calls.push(`writeTs:${path}`); stor[path] = source; return true; },
    writeText: async (path, content) => { calls.push(`writeText:${path}`); stor[path] = content; return true; },
    compile: async (sources, hashes) => {
      calls.push('compile');
      return compileOver ? compileOver(sources) : sources.map(s => ({ path: s.path, sha256: hashes.get(s.path) || '', status: 'passed' as const, diagnostics: [] }));
    },
    writeJson: async (info, value) => { traces.push({ info, value }); },
    failure: {
      recordDegradation: async kind => { failures.push(`record:${kind}`); },
      saveSummary: async summary => { failures.push(`summary:${summary.verdict}`); return null; },
      readRun: async () => null,
      now: () => new Date(),
    },
  };
  return { port, stor, calls, traces, failures };
}

test('golden: produtos is byte for byte the approved client', async () => {
  const input = await realInput();
  const page = input.pages.find(item => item.pageId === 'produtos')!;
  assert.equal(renderM3ContractClient(PROJECT, MODULE, 'produtos', page.requests), GOLDEN_PRODUTOS);
});

test('golden: movimentacoes routes are load and registrarMovimentacao', async () => {
  const input = await realInput();
  const page = input.pages.find(item => item.pageId === 'movimentacoes')!;
  assert.deepEqual(page.requests.map(item => item.route), ['controleEstoque.movimentacoes.load', 'controleEstoque.movimentacoes.registrarMovimentacao']);
  assert.equal(renderM3ContractClient(PROJECT, MODULE, 'movimentacoes', page.requests), GOLDEN_MOVIMENTACOES);
});

test('the output carries the ownership marker and never uses any', async () => {
  const input = await realInput();
  for (const page of input.pages) {
    const source = renderM3ContractClient(PROJECT, MODULE, page.pageId, page.requests);
    assert.ok(source.includes(M3_CONTRACT_MARKER));
    assert.doesNotMatch(source, /\bany\b/u);
  }
});

test('a clean run writes, compiles and gives a receipt to every page', async () => {
  const input = await realInput();
  const { port, stor, calls, traces, failures } = makePort(input);
  const result = await executeM3Contracts(port, identity);
  assert.equal(result.status, 'completed');
  assert.equal(stor[outPath('produtos')], GOLDEN_PRODUTOS);
  const receipt = JSON.parse(stor[`_${PROJECT}_/l2/${MODULE}/web/contracts/produtosReceipt.json`]);
  assert.equal(receipt.outputHash, await sha256Text(GOLDEN_PRODUTOS));
  assert.deepEqual(receipt.usedApis.map((item: any) => item.reference), ['_102029_/l2/bffClient.ts', '_102047_/l2/controleEstoque/web/contracts/produtos.defs.ts']);
  assert.deepEqual(traces[0].value.pages.map((item: any) => item.status), ['written', 'written']);
  assert.equal(traces[0].info.shortName, 'contracts30');
  assert.deepEqual(failures, []);
  assert.equal(calls.filter(call => call === 'compile').length, 2);
});

test('a second run reuses a fresh receipt: no write, no compile, no new receipt', async () => {
  const input = await realInput();
  const first = makePort(input);
  await executeM3Contracts(first.port, identity);
  const second = makePort(input, first.stor);
  const result = await executeM3Contracts(second.port, identity);
  assert.equal(result.status, 'completed');
  assert.deepEqual(second.calls, []);
  assert.deepEqual(second.traces[0].value.pages.map((item: any) => item.status), ['reused', 'reused']);
});

test('a file of another owner is M3_FOREIGN_FILE and is never written', async () => {
  const input = await realInput();
  const { port, calls, traces, failures } = makePort(input, { [outPath('produtos')]: 'export const handmade = 1;\n' });
  const result = await executeM3Contracts(port, identity);
  assert.equal(result.status, 'failed');
  assert.match((result as { reason: string }).reason, /produtos: M3_FOREIGN_FILE: _102047_\/l2\/controleEstoque\/web\/contracts\/produtos\.ts/u);
  assert.ok(!calls.includes(`writeTs:${outPath('produtos')}`));
  assert.equal(traces[0].value.pages.find((item: any) => item.pageId === 'produtos').status, 'failed');
  assert.equal(traces[0].value.pages.find((item: any) => item.pageId === 'movimentacoes').status, 'written');
  assert.deepEqual(failures, ['record:M3_FOREIGN_FILE', 'summary:failed']);
});

test('a compile error fails the page, keeps the diagnostic in the trace and writes no receipt', async () => {
  const input = await realInput();
  const { port, stor, traces } = makePort(input, {}, sources => sources.map(s => ({ path: s.path, sha256: 'sha256:x', status: 'failed' as const, diagnostics: ['TS2322: bad'] })));
  const result = await executeM3Contracts(port, identity);
  assert.equal(result.status, 'failed');
  assert.match((result as { reason: string }).reason, /M3_CONTRACT_COMPILE_FAILED: TS2322: bad/u);
  assert.deepEqual(traces[0].value.pages[0].compile.diagnostics, ['TS2322: bad']);
  assert.equal(stor[`_${PROJECT}_/l2/${MODULE}/web/contracts/produtosReceipt.json`], undefined);
});

test('a missing input.json fails with M3_INPUT_MISSING and leaves the failure records', async () => {
  const { port, failures } = makePort(null);
  const result = await executeM3Contracts(port, identity);
  assert.equal(result.status, 'failed');
  assert.match((result as { reason: string }).reason, /^M3_INPUT_MISSING/u);
  assert.deepEqual(failures, ['record:M3_INPUT_MISSING', 'summary:failed']);
});

test('an identical .ts without receipt is unchanged: receipt written, .ts not rewritten', async () => {
  const input = await realInput();
  const { port, calls, traces } = makePort(input, { [outPath('produtos')]: GOLDEN_PRODUTOS });
  const result = await executeM3Contracts(port, identity);
  assert.equal(result.status, 'completed');
  assert.equal(traces[0].value.pages.find((item: any) => item.pageId === 'produtos').status, 'unchanged');
  assert.equal(traces[0].value.pages.find((item: any) => item.pageId === 'movimentacoes').status, 'written');
  assert.ok(!calls.includes(`writeTs:${outPath('produtos')}`));
  assert.ok(calls.includes(`writeText:_${PROJECT}_/l2/${MODULE}/web/contracts/produtosReceipt.json`));
});

test('an absent .ts is written', async () => {
  const input = await realInput();
  const { port, calls, traces } = makePort(input);
  await executeM3Contracts(port, identity);
  assert.equal(traces[0].value.pages.find((item: any) => item.pageId === 'produtos').status, 'written');
  assert.ok(calls.includes(`writeTs:${outPath('produtos')}`));
});

test('D-011: the production port writes without an editor model', () => {
  const source = readFileSync(fileURLToPath(new URL('./run.ts', import.meta.url)), 'utf8');
  assert.ok(!source.includes('saveGeneratedTs'));
  assert.ok(source.includes('writeTs: saveArtifactTextByMlsPath'));
});
