/// <mls fileReference="_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vTemplates.ts" enhancement="_blank"/>

// Deterministic renderers for the variant's shell files (Strategy D) and the
// demo-state substitution. Pure string functions — the templates mirror the
// hand-made variants of mls-102054/102055 (fase 0 findings, todo 0.2).

import { VariantContext } from '/_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vContext.js';
import { toShellTitle } from '/_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vOrigin.js';

export function renderShellTs(ctx: VariantContext): string {
  const title = toShellTitle(ctx.origin.shortName);
  const themeUpper = ctx.theme.info.displayName.toUpperCase();
  const portalBlock = ctx.origin.portal
    ? `\n  // O container do portal (document.body) recebe este data-widget — o .less do\n  // tema escopa o painel por div[data-widget="..."].\n  protected portalWidgetName = '${ctx.variant.tag}';\n`
    : '';
  const inherits = ctx.origin.portal ? 'inclusive render() e getPortalTemplate()' : 'inclusive render()';
  const body = ctx.origin.portal ? `{${portalBlock}}` : '{}';
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.ts" enhancement="_102020_/l2/enhancementAura"/>
// =============================================================================
// ${title} — ${themeUpper} (mls-${ctx.theme.project})
// =============================================================================
// Skill Group: ${ctx.origin.groupCanonical}
// Casca (estratégia D): herda tudo de ${ctx.origin.className} (mls-${ctx.origin.project}),
// ${inherits} — o markup base emite classes semânticas ml-*; a aparência
// vem do .less irmão, escopado sob esta tag.
// This molecule does NOT contain business logic.
import { customElement } from 'lit/decorators.js';
import { ${ctx.origin.className} } from '${ctx.origin.importPath}';

@customElement('${ctx.variant.tag}')
export class ${ctx.variant.className} extends ${ctx.origin.className} ${body}
`;
}

// The .defs.ts is a CONTRACT consumed by other collab routines (e.g. the DS
// agent reads layoutConfig; other routines read the skill responsibilities /
// constraints). The variant inherits ALL behavior from the origin (Strategy D),
// so its contract is IDENTICAL — we replicate the origin defs VERBATIM and swap
// only the two identity fields that must reflect THIS file: the mls header
// fileReference and the skill's TagName line.
export function renderShellDefs(ctx: VariantContext, originDefs: string): string {
  const source = originDefs.replace(/^﻿/, '');
  if (!source.trim()) throw new Error('[vTemplates] origin .defs.ts is empty — cannot replicate the component contract');
  const withTag = source.replace(/^(\s*-\s*TagName:\s*).*$/m, `$1${ctx.variant.tag}`);
  return swapDefsHeader(withTag, ctx);
}

// The mls header identifies WHICH file this is (M2 lesson: a wrong project in
// the header breaks file identity). Replace the origin's header line with the
// variant's; if the file somehow has no header, prepend one.
export function renderDefsHeader(ctx: VariantContext): string {
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.defs.ts" enhancement="_blank" />`;
}

function swapDefsHeader(defs: string, ctx: VariantContext): string {
  const lines = defs.split('\n');
  if (/^\s*\/\/\/\s*<mls\b/.test(lines[0])) {
    lines[0] = renderDefsHeader(ctx);
    return lines.join('\n');
  }
  return `${renderDefsHeader(ctx)}\n${defs}`;
}

// The group index page (index.ts) is generated by the v4-index LLM step reusing
// the shared indexGroupPage skill. index.html is deterministic — just the group
// index custom element tag.
export function groupIndexTag(ctx: VariantContext): string {
  return `molecules--${ctx.variant.group}--index-${ctx.theme.project}`;
}

export function renderGroupIndexHtml(ctx: VariantContext): string {
  const indexTag = groupIndexTag(ctx);
  return `<${indexTag}></${indexTag}>`;
}

// M2: the mls header is a METADATA line owned by code, never by the LLM (the
// model copies it from the reference sheet and gets the project wrong). The
// canonical .less header (verified on real 102054/102055 variants):
export function renderLessHeader(ctx: VariantContext): string {
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.less" enhancement="_102020_/l2/enhancementStyleAura" />`;
}

// Strip any leading `/// <mls ...>` line(s) the model emitted (and the blank
// line right after), so the deterministic header can replace them.
export function stripLeadingMlsHeader(content: string): string {
  const lines = content.split('\n');
  let i = 0;
  while (i < lines.length && (/^\s*\/\/\/\s*<mls\b/.test(lines[i]) || lines[i].trim() === '')) {
    // Stop consuming blank lines once a non-header, non-blank line is reached.
    if (lines[i].trim() === '' && i > 0 && !/^\s*\/\/\/\s*<mls\b/.test(lines[i - 1])) break;
    i++;
  }
  return lines.slice(i).join('\n');
}

// Normalize the generated sheet: enforce the correct header, dropping whatever
// header the LLM produced. Used by v3-less before the gate + write.
export function normalizeLessContent(lessRaw: string, ctx: VariantContext): string {
  const body = stripLeadingMlsHeader(lessRaw).replace(/^\n+/, '');
  return `${renderLessHeader(ctx)}\n${body}`;
}

// Port of agentNewMoleculePlayground.generatePlaygroundState (fase 0.3): the demo
// html carries a 'playgroundDinamicState' placeholder that is replaced
// DETERMINISTICALLY by the state assembled from the LLM examples.
export interface VDemoExample {
  name: string;
  state: { stateName: string; value: string }[];
}

export function substituteDemoState(html: string, examples: VDemoExample[]): string {
  const playground: Record<string, Record<string, unknown>> = {};
  for (const scenario of examples) {
    for (const entry of scenario.state || []) {
      const parts = entry.stateName.split('.');
      if (parts.length !== 3 || parts[0] !== 'playground') continue;
      const key = parts[1];
      const prop = parts[2];
      let parsed: unknown;
      try {
        parsed = JSON.parse(entry.value);
      } catch {
        parsed = entry.value;
      }
      if (!playground[key]) playground[key] = {};
      playground[key][prop] = parsed;
    }
  }
  return html.replace('playgroundDinamicState', JSON.stringify({ playground }));
}
