/// <mls fileReference="_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vTemplates.ts" enhancement="_blank"/>

// Deterministic renderers for the variant's shell files (Strategy D) and the
// demo-state substitution. Pure string functions — the templates mirror the
// hand-made variants of mls-102054/102055 (fase 0 findings, todo 0.2).

import { VariantContext } from '/_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vContext.js';
import { toShellTitle } from '/_102020_/l2/aura/molecules/agentNewMoleculeVariant/helpers/vOrigin.js';
import {
  stripLeadingMlsHeader as sharedStripLeadingMlsHeader,
  substituteDemoState as sharedSubstituteDemoState,
  type MoleculeDemoExample,
} from '/_102020_/l2/aura/molecules/shared/moleculeTemplates.js';

// Header stripping and the playground-state substitution are the SAME problem in every molecule
// artifact, so they live in shared/moleculeTemplates (agentNewMolecule2 consumes them too).
// Re-exported here under their original names so this module's importers are unaffected.
export { sharedStripLeadingMlsHeader as stripLeadingMlsHeader, sharedSubstituteDemoState as substituteDemoState };
export type VDemoExample = MoleculeDemoExample;

export function renderShellTs(ctx: VariantContext): string {
  const title = toShellTitle(ctx.origin.shortName);
  const themeUpper = ctx.theme.info.displayName.toUpperCase();
  const portalBlock = ctx.origin.portal
    ? `\n  // The portal container (document.body) receives this data-widget — the theme\n  // .less scopes the panel via div[data-widget="..."].\n  protected portalWidgetName = '${ctx.variant.tag}';\n`
    : '';
  const inherits = ctx.origin.portal ? 'including render() and getPortalTemplate()' : 'including render()';
  const body = ctx.origin.portal ? `{${portalBlock}}` : '{}';
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.ts" enhancement="_102020_/l2/enhancementAura"/>
// =============================================================================
// ${title} — ${themeUpper} (mls-${ctx.theme.project})
// =============================================================================
// Skill Group: ${ctx.origin.groupCanonical}
// Shell (Strategy D): inherits everything from ${ctx.origin.className} (mls-${ctx.origin.project}),
// ${inherits} — the base markup emits semantic ml-* classes; the appearance
// comes from the sibling .less, scoped under this tag.
// This molecule does NOT contain business logic.
import { customElement } from 'lit/decorators.js';
import { ${ctx.origin.className} } from '${ctx.origin.importPath}';

@customElement('${ctx.variant.tag}')
export class ${ctx.variant.className} extends ${ctx.origin.className} ${body}
`;
}

// The .defs.ts is a CONTRACT consumed by other collab routines (e.g. the DS
// agent reads layoutConfig; other routines read the skill responsibilities /
// constraints). The variant inherits ALL behavior from the origin (Strategy D),
// so its contract is IDENTICAL — we replicate the origin defs VERBATIM and swap
// only the two identity fields that must reflect THIS file: the mls header
// fileReference and the skill's TagName line.
export function renderShellDefs(ctx: VariantContext, originDefs: string): string {
  const source = originDefs.replace(/^﻿/, '');
  if (!source.trim()) throw new Error('[vTemplates] origin .defs.ts is empty — cannot replicate the component contract');
  const withTag = source.replace(/^(\s*-\s*TagName:\s*).*$/m, `$1${ctx.variant.tag}`);
  return swapDefsHeader(withTag, ctx);
}

// The mls header identifies WHICH file this is (M2 lesson: a wrong project in
// the header breaks file identity). Replace the origin's header line with the
// variant's; if the file somehow has no header, prepend one.
export function renderDefsHeader(ctx: VariantContext): string {
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.defs.ts" enhancement="_blank" />`;
}

function swapDefsHeader(defs: string, ctx: VariantContext): string {
  const lines = defs.split('\n');
  if (/^\s*\/\/\/\s*<mls\b/.test(lines[0])) {
    lines[0] = renderDefsHeader(ctx);
    return lines.join('\n');
  }
  return `${renderDefsHeader(ctx)}\n${defs}`;
}

// The group index page (index.ts) is generated by the v4-index LLM step reusing
// the shared indexGroupPage skill. index.html is deterministic — just the group
// index custom element tag.
export function groupIndexTag(ctx: VariantContext): string {
  return `molecules--${ctx.variant.group}--index-${ctx.theme.project}`;
}

export function renderGroupIndexHtml(ctx: VariantContext): string {
  const indexTag = groupIndexTag(ctx);
  return `<${indexTag}></${indexTag}>`;
}

// M2: the mls header is a METADATA line owned by code, never by the LLM (the
// model copies it from the reference sheet and gets the project wrong). The
// canonical .less header (verified on real 102054/102055 variants):
export function renderLessHeader(ctx: VariantContext): string {
  return `/// <mls fileReference="_${ctx.theme.project}_/l2/molecules/${ctx.variant.group}/${ctx.variant.shortName}.less" enhancement="_102020_/l2/enhancementStyleAura" />`;
}

// Normalize the generated sheet: enforce the correct header, dropping whatever
// header the LLM produced. Used by v3-less before the gate + write.
export function normalizeLessContent(lessRaw: string, ctx: VariantContext): string {
  const body = sharedStripLeadingMlsHeader(lessRaw).replace(/^\n+/, '');
  return `${renderLessHeader(ctx)}\n${body}`;
}

// The demo-state substitution (formerly a port of
// agentNewMoleculePlayground.generatePlaygroundState) now lives in shared/moleculeTemplates
// and is re-exported at the top of this file, together with the VDemoExample type.
