/// <mls fileReference="_102020_/l2/aura/molecules/agentNewTheme/helpers/ntThemeHtml.ts" enhancement="_blank"/>

// Deterministic renderer of l2/skills/theme.html — the theme's documentation/preview
// page, built from the SAME structured summary that feeds Checkpoint 2 (no second LLM
// call, so page and confirmation can never disagree). It is NOT part of the contract the
// molecule agents consume (they read only theme.ts). Pure — unit-testable.
// Like the molecule demo pages, it is an HTML FRAGMENT (no doctype/head/body).

import { NtThemeSummary } from '/_102020_/l2/aura/molecules/agentNewTheme/helpers/ntTypes.js';

export interface NtThemeHtmlInputs {
  summary: NtThemeSummary;
  description?: string;
  suffix?: string;
}

export function renderThemeHtml(inputs: NtThemeHtmlInputs): string {
  const { summary } = inputs;
  const onDark = summary.background.kind !== 'light';
  const text = onDark ? 'rgba(255,255,255,0.92)' : 'rgba(15,23,42,0.92)';
  const muted = onDark ? 'rgba(255,255,255,0.62)' : 'rgba(15,23,42,0.62)';
  const cardBg = onDark ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.72)';
  const line = onDark ? 'rgba(255,255,255,0.18)' : 'rgba(15,23,42,0.12)';

  return `<!-- Generated by agentNewTheme from l2/skills/theme.ts — documentation page, not part of the theme contract. -->
<div style="min-height:100vh; padding:2rem; ${escapeAttr(summary.background.css)} background-attachment:fixed;">
  <div style="max-width:64rem; margin:0 auto; color:${text}; font-family:system-ui,sans-serif;">
    <header style="margin-bottom:2.5rem;">
      <h1 style="font-size:2rem; font-weight:700; margin:0 0 0.5rem;">${escapeHtml(summary.displayName)}</h1>
      <p style="margin:0; color:${muted};">${escapeHtml(inputs.description || '')}</p>
      <p style="margin:0.5rem 0 0; color:${muted}; font-size:0.875rem;">
        <code>${escapeHtml(summary.name)}</code>${inputs.suffix ? ` · suffix <code>${escapeHtml(inputs.suffix)}</code>` : ''} · background <code>${escapeHtml(summary.background.kind)}</code>
      </p>
    </header>

    <section style="margin-bottom:2.5rem;">
      <h2 style="font-size:1.125rem; font-weight:600; margin:0 0 1rem;">Palette</h2>
      <div style="display:flex; flex-wrap:wrap; gap:0.75rem;">
${summary.palette.map(swatch => renderSwatch(swatch.token, swatch.label, swatch.color, muted, line)).join('\n')}
      </div>
    </section>

    <section>
      <h2 style="font-size:1.125rem; font-weight:600; margin:0 0 1rem;">Signature</h2>
      <div style="background:${cardBg}; border:1px solid ${line}; border-radius:0.5rem; overflow:hidden;">
        <table style="width:100%; border-collapse:collapse; font-size:0.9375rem;">
          <tbody>
${summary.signature.map(row => `            <tr><th style="text-align:left; padding:0.625rem 1rem; width:12rem; font-weight:600; border-bottom:1px solid ${line};">${escapeHtml(row.aspect)}</th><td style="padding:0.625rem 1rem; border-bottom:1px solid ${line}; color:${muted};">${escapeHtml(row.value)}</td></tr>`).join('\n')}
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>
`;
}

function renderSwatch(token: string, label: string, color: string, muted: string, line: string): string {
  return `        <div style="width:9.5rem;">
          <div style="height:4rem; border-radius:0.5rem; border:1px solid ${line}; background:${escapeAttr(color)};"></div>
          <div style="margin-top:0.375rem; font-size:0.8125rem; font-weight:600;">${escapeHtml(label)}</div>
          <div style="font-size:0.75rem; color:${muted};"><code>${escapeHtml(token)}</code></div>
          <div style="font-size:0.75rem; color:${muted};">${escapeHtml(color)}</div>
        </div>`;
}

function escapeHtml(value: string): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Values that land inside a style attribute: kill the quote/angle characters that
// would break out of the attribute (the summary comes from an LLM).
function escapeAttr(value: string): string {
  return String(value ?? '').replace(/["<>]/g, '');
}
