/// <mls fileReference="_102020_/l2/aura/molecules/agentNewTheme/helpers/ntThemeHtml.ts" enhancement="_blank"/>

// Deterministic renderer of l2/skills/theme.html — the theme's documentation/preview
// page, built from the SAME structured summary the step view shows (no second LLM call,
// so page and step view can never disagree). It is NOT part of the contract the
// molecule agents consume (they read only theme.ts). Pure — unit-testable.
// Like the molecule demo pages, it is an HTML FRAGMENT (no doctype/head/body).

import { NtThemeSummary } from '/_102020_/l2/aura/molecules/agentNewTheme/helpers/ntTypes.js';

export interface NtThemeHtmlInputs {
  summary: NtThemeSummary;
  description?: string;
  suffix?: string;
}

// The doc page borrows the theme's OWN geometry (T6): a page documenting a zero-radius
// monospace theme should not be rendered in rounded system-ui cards. Read tolerantly from
// the signature rows, with neutral fallbacks — the values are LLM prose, not a contract.
export interface NtThemeChrome {
  radius: string;
  border: string;
  fontFamily: string;
}

export function deriveThemeChrome(summary: NtThemeSummary, fallbackLine: string): NtThemeChrome {
  const row = (pattern: RegExp): string => (summary.signature || []).find(item => pattern.test(item.aspect || ''))?.value || '';

  const cornersRow = row(/corner|radius|shape/i);
  const radiusMatch = cornersRow.match(/(\d+(?:\.\d+)?)\s*(px|rem)/i);
  const sharp = /\b(0|none|sharp|square|hard)\b/i.test(cornersRow);
  let radius = '0.5rem';
  if (radiusMatch) {
    const value = Math.min(Number(radiusMatch[1]), radiusMatch[2].toLowerCase() === 'rem' ? 1.5 : 24);
    radius = `${value}${radiusMatch[2].toLowerCase()}`;
  } else if (sharp) {
    radius = '0';
  }

  const borderRow = row(/border|outline|edge/i);
  const widthMatch = borderRow.match(/(\d+(?:\.\d+)?)\s*px/i);
  const colorMatch = borderRow.match(/#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)/);
  const width = widthMatch ? Math.min(Number(widthMatch[1]), 6) : 1;
  const border = `${width}px solid ${colorMatch ? colorMatch[0] : fallbackLine}`;

  const typographyRow = row(/typograph|font|type\b/i);
  let fontFamily = 'system-ui,sans-serif';
  if (/mono/i.test(typographyRow)) fontFamily = 'ui-monospace,SFMono-Regular,Menlo,monospace';
  else if (/serif/i.test(typographyRow) && !/sans[- ]?serif/i.test(typographyRow)) fontFamily = 'Georgia,Cambria,serif';

  return { radius, border, fontFamily };
}

export function renderThemeHtml(inputs: NtThemeHtmlInputs): string {
  const { summary } = inputs;
  const onDark = summary.background.kind !== 'light';
  const text = onDark ? 'rgba(255,255,255,0.92)' : 'rgba(15,23,42,0.92)';
  const muted = onDark ? 'rgba(255,255,255,0.62)' : 'rgba(15,23,42,0.62)';
  const cardBg = onDark ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.72)';
  const line = onDark ? 'rgba(255,255,255,0.18)' : 'rgba(15,23,42,0.12)';
  const chrome = deriveThemeChrome(summary, line);

  return `<!-- Generated by agentNewTheme from l2/skills/theme.ts — documentation page, not part of the theme contract. -->
<div style="min-height:100vh; padding:2rem; ${escapeAttr(summary.background.css)} background-attachment:fixed;">
  <div style="max-width:64rem; margin:0 auto; color:${text}; font-family:${chrome.fontFamily};">
    <header style="margin-bottom:2.5rem;">
      <h1 style="font-size:2rem; font-weight:700; margin:0 0 0.5rem;">${escapeHtml(summary.displayName)}</h1>
      <p style="margin:0; color:${muted};">${escapeHtml(inputs.description || '')}</p>
      <p style="margin:0.5rem 0 0; color:${muted}; font-size:0.875rem;">
        <code>${escapeHtml(summary.name)}</code>${inputs.suffix ? ` · suffix <code>${escapeHtml(inputs.suffix)}</code>` : ''} · background <code>${escapeHtml(summary.background.kind)}</code>
      </p>
    </header>

    <section style="margin-bottom:2.5rem;">
      <h2 style="font-size:1.125rem; font-weight:600; margin:0 0 1rem;">Palette</h2>
      <div style="display:flex; flex-wrap:wrap; gap:0.75rem;">
${summary.palette.map(swatch => renderSwatch(swatch.token, swatch.label, swatch.color, muted, chrome)).join('\n')}
      </div>
    </section>

    <section>
      <h2 style="font-size:1.125rem; font-weight:600; margin:0 0 1rem;">Signature</h2>
      <div style="background:${cardBg}; border:${chrome.border}; border-radius:${chrome.radius}; overflow:hidden;">
        <table style="width:100%; border-collapse:collapse; font-size:0.9375rem;">
          <tbody>
${summary.signature.map(row => `            <tr><th style="text-align:left; padding:0.625rem 1rem; width:12rem; font-weight:600; border-bottom:1px solid ${line};">${escapeHtml(row.aspect)}</th><td style="padding:0.625rem 1rem; border-bottom:1px solid ${line}; color:${muted};">${escapeHtml(row.value)}</td></tr>`).join('\n')}
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>
`;
}

function renderSwatch(token: string, label: string, color: string, muted: string, chrome: NtThemeChrome): string {
  return `        <div style="width:9.5rem;">
          <div style="height:4rem; border-radius:${chrome.radius}; border:${chrome.border}; background:${escapeAttr(color)};"></div>
          <div style="margin-top:0.375rem; font-size:0.8125rem; font-weight:600;">${escapeHtml(label)}</div>
          <div style="font-size:0.75rem; color:${muted};"><code>${escapeHtml(token)}</code></div>
          <div style="font-size:0.75rem; color:${muted};">${escapeHtml(color)}</div>
        </div>`;
}

function escapeHtml(value: string): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Values that land inside a style attribute: kill the quote/angle characters that
// would break out of the attribute (the summary comes from an LLM).
function escapeAttr(value: string): string {
  return String(value ?? '').replace(/["<>]/g, '');
}
