/// <mls fileReference="_102020_/l2/dsMatch/buildGlobalCss.ts" enhancement="_blank" />

// Deterministic Design-System stylesheet generator (Phase B styling).
//
// Reads every `designSystems[*].tokens` from project.json and emits ONE project-wide
// stylesheet at `_<project>_/l2/styles/global.css`. Each DS becomes a class-scoped block:
//
//   .ds-<name>      { --ds-*: <light value>; … }   // light (base)
//   .dark .ds-<name>{ --ds-*: <dark value>;  … }   // dark — preview toggles the `.dark` class
//
// A page applies `class="ds-<name>"` on its root; because Aura components render in light DOM
// (createRenderRoot returns this), the `--ds-*` variables cascade into the whole tree, including
// composed molecules and their slot tags. Pure token→CSS transform — no LLM. Run once, project-wide
// (the `register` terminal step of agentImplementsDesignSystem2). Editing a token value only
// regenerates this file; pages that reference `var(--ds-*)` need no re-generation.

import { createStorFile } from '/_102027_/l2/libStor.js';
import { getConfigProject } from '/_102027_/l2/libProjectConfig.js';

// ─── Token shape (the contract adopted on designSystems[ds].tokens) ──────────────
export interface DsColorRole { light: string; dark: string; }
export interface DsTokens {
    palette?: string[];                              // authoring-only; never emitted
    color?: Record<string, DsColorRole>;
    typography?: {
        fontDisplay?: string;
        fontBody?: string;
        scale?: string;                              // applied via Tailwind classes by the render skill
        weightHeading?: string;
        weightBody?: string;
        tracking?: string;
    };
    shape?: { radius?: string; borderWidth?: string };
    density?: string;                                // applied via Tailwind classes
    elevation?: string;                              // applied via Tailwind classes
}

/** Canonical file reference of the project-wide DS stylesheet (single source of truth:
 *  both the writer and the page-defs `dependsFiles` entry use this). */
export const dsGlobalCssRef = (project: number): string => `_${project}_/l2/styles/global.css`;

// Color role → CSS var name (most roles map 1:1; `background` shortens to `bg`).
const COLOR_VAR_ALIAS: Record<string, string> = { background: 'bg' };
const colorVar = (role: string) => `--ds-${COLOR_VAR_ALIAS[role] ?? role}`;

// Semantic radius scale → concrete length (mirrors Tailwind's rounded-* values).
const RADIUS_LENGTH: Record<string, string> = {
    none: '0',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    full: '9999px',
};

/** Slug for the parent class: lowercase, non-alphanumerics collapsed to a dash. */
export function dsClassName(name: string): string {
    const slug = String(name).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    return `ds-${slug || 'unnamed'}`;
}

function borderWidthLength(value: string | undefined): string | null {
    if (value == null) return null;
    const v = String(value).trim();
    if (!v) return null;
    return /^\d+$/.test(v) ? `${v}px` : v;
}

/** Theme-independent vars (fonts, shape) — emitted only in the light/base block. */
function staticVars(tokens: DsTokens): string[] {
    const out: string[] = [];
    const t = tokens.typography ?? {};
    if (t.fontDisplay) out.push(`--ds-font-display: ${t.fontDisplay};`);
    if (t.fontBody) out.push(`--ds-font-body: ${t.fontBody};`);
    const radius = tokens.shape?.radius;
    if (radius && RADIUS_LENGTH[radius] != null) out.push(`--ds-radius: ${RADIUS_LENGTH[radius]};`);
    const bw = borderWidthLength(tokens.shape?.borderWidth);
    if (bw) out.push(`--ds-border-w: ${bw};`);
    return out;
}

/** Color vars for one variant ('light' | 'dark'). */
function colorVars(tokens: DsTokens, variant: 'light' | 'dark'): string[] {
    const color = tokens.color ?? {};
    return Object.entries(color)
        .filter(([, role]) => role && typeof role[variant] === 'string')
        .map(([roleName, role]) => `${colorVar(roleName)}: ${role[variant]};`);
}

/** One DS → its `.ds-<name>` (light) + `.dark .ds-<name>` (dark) blocks. */
export function tokensToCss(name: string, tokens: DsTokens): string {
    const cls = dsClassName(name);
    const indent = (lines: string[]) => lines.map(l => `  ${l}`).join('\n');

    const light = [...colorVars(tokens, 'light'), ...staticVars(tokens)];
    const dark = colorVars(tokens, 'dark');

    const blocks: string[] = [];
    if (light.length) blocks.push(`.${cls} {\n${indent(light)}\n}`);
    if (dark.length) blocks.push(`.dark .${cls} {\n${indent(dark)}\n}`);
    return blocks.join('\n\n');
}

/** Build the full stylesheet string from a project's designSystems map. */
export function renderGlobalCss(designSystems: Record<string, { name?: string; tokens?: DsTokens }>): string {
    const header = '/* AUTO-GENERATED by dsMatch/buildGlobalCss — do not edit by hand. */';
    const entries = Object.entries(designSystems ?? {})
        .filter(([, ds]) => ds && ds.tokens && typeof ds.tokens === 'object')
        .sort(([a], [b]) => Number(a) - Number(b));

    const blocks = entries
        .map(([, ds]) => tokensToCss(ds.name ?? 'default', ds.tokens as DsTokens))
        .filter(Boolean);

    return [header, ...blocks].join('\n\n') + '\n';
}

// ─── stor I/O ────────────────────────────────────────────────────────────────────

/** Create or overwrite a file by file reference (mirrors planning.saveFile). */
async function writeFileByRef(ref: string, src: string): Promise<void> {
    const info = mls.stor.convertFileReferenceToFile(ref);
    const key = mls.stor.getKeyToFile(info);
    let sf = mls.stor.files[key];
    if (!sf) {
        sf = await createStorFile({ ...info, source: src } as any, true, true, true);
    } else {
        const m = await sf.getOrCreateModel();
        if (m && m.model) m.model.setValue(src);
    }
    await mls.stor.localStor.setContent(sf, { contentType: 'string', content: src });
}

/**
 * Regenerate `_<project>_/l2/styles/global.css` from the project's designSystems tokens.
 * Idempotent — rewrites the whole file. Returns the CSS written.
 */
export async function buildGlobalCss(project: number): Promise<string> {
    const config: any = await getConfigProject(project);
    const designSystems = (config?.designSystems && typeof config.designSystems === 'object')
        ? config.designSystems
        : {};
    const css = renderGlobalCss(designSystems);
    await writeFileByRef(dsGlobalCssRef(project), css);
    return css;
}

/** Read the generated DS stylesheet for the preview (empty string when absent). */
export async function readDsGlobalCss(project: number): Promise<string> {
    try {
        const info = mls.stor.convertFileReferenceToFile(dsGlobalCssRef(project));
        const key = mls.stor.getKeyToFile(info);
        const sf = mls.stor.files[key];
        if (!sf) return '';
        const content = await sf.getContent();
        return typeof content === 'string' ? content : '';
    } catch {
        return '';
    }
}
